version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smarttransit-app
    env_file:
      - .env.local
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - REDIS_URL=redis://:secretredispassword@redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: smarttransit-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass secretredispassword
    volumes:
      - redis_data:/data

volumes:
  redis_data: